services:
  langflow:
    image: langflowai/langflow:latest # or another version tag on https://hub.docker.com/r/langflowai/langflow
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - LANGFLOW_CONFIG_DIR=app/langflow
    volumes:
      - langflow-data:/app/langflow

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    entrypoint: >
      sh -c "ollama serve &
      sleep 5;
      ollama pull $OLLAMA_LLM;
      ollama pull $OLLAMA_EMBEDDING_MODEL;
      wait
      "

  chat-bot:
    container_name: chat-bot
    build:
      context: chat-bot
      dockerfile: Dockerfile
    env_file:
      - ".env"
    restart: always
    depends_on:
      - langflow
      - ollama

volumes:
  langflow-postgres:
  langflow-data:
  ollama:

